### ISSUE TITLE
Feature 1: User can NBA Conference (Western Conference / Eastern Conference).

### ISSUE THREAD

**Issue by jeffmjin** [jeffmjin/ajax-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the 2 NBA Conferences

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Create the page where the user can view each conference.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="613" alt="Screen Shot 2022-09-26 at 9 39 47 AM" src="https://user-images.githubusercontent.com/110066310/192333539-2b187232-1440-4e38-92a1-7dc5154ce2ed.png">
<img width="162" alt="Screen Shot 2022-09-26 at 9 39 56 AM" src="https://user-images.githubusercontent.com/110066310/192333558-a29e74fe-ce67-4708-b38e-6d79d0471890.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ]  Add a div to show both conferences. *(images have been provided)*
- [ ] Ensure that the form looks nice on both mobile-sized and desktop-sized screens.
- [ ] Listen for 'click' events on each image that will show the divisions in each conference *(leave it blank for now)*
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
